development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:8161acca578dd7fa8ba54d148cb1caca@scat.redistogo.com:9663/
  channel_prefix: message_me_production
